/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/answers": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.answers.id"];
          created_at?: parameters["rowFilter.answers.created_at"];
          text?: parameters["rowFilter.answers.text"];
          problem?: parameters["rowFilter.answers.problem"];
          isCorrect?: parameters["rowFilter.answers.isCorrect"];
          desc?: parameters["rowFilter.answers.desc"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["answers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** answers */
          answers?: definitions["answers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.answers.id"];
          created_at?: parameters["rowFilter.answers.created_at"];
          text?: parameters["rowFilter.answers.text"];
          problem?: parameters["rowFilter.answers.problem"];
          isCorrect?: parameters["rowFilter.answers.isCorrect"];
          desc?: parameters["rowFilter.answers.desc"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.answers.id"];
          created_at?: parameters["rowFilter.answers.created_at"];
          text?: parameters["rowFilter.answers.text"];
          problem?: parameters["rowFilter.answers.problem"];
          isCorrect?: parameters["rowFilter.answers.isCorrect"];
          desc?: parameters["rowFilter.answers.desc"];
        };
        body: {
          /** answers */
          answers?: definitions["answers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/user": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          created_at?: parameters["rowFilter.user.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["user"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** user */
          user?: definitions["user"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          created_at?: parameters["rowFilter.user.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          created_at?: parameters["rowFilter.user.created_at"];
        };
        body: {
          /** user */
          user?: definitions["user"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/problem": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.problem.id"];
          created_at?: parameters["rowFilter.problem.created_at"];
          title?: parameters["rowFilter.problem.title"];
          code?: parameters["rowFilter.problem.code"];
          score?: parameters["rowFilter.problem.score"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["problem"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** problem */
          problem?: definitions["problem"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.problem.id"];
          created_at?: parameters["rowFilter.problem.created_at"];
          title?: parameters["rowFilter.problem.title"];
          code?: parameters["rowFilter.problem.code"];
          score?: parameters["rowFilter.problem.score"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.problem.id"];
          created_at?: parameters["rowFilter.problem.created_at"];
          title?: parameters["rowFilter.problem.title"];
          code?: parameters["rowFilter.problem.code"];
          score?: parameters["rowFilter.problem.score"];
        };
        body: {
          /** problem */
          problem?: definitions["problem"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  answers: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    text?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `problem.id`.<fk table='problem' column='id'/>
     */
    problem?: number;
    /**
     * Format: boolean
     * @default false
     */
    isCorrect?: boolean;
    /** Format: text */
    desc?: string;
  };
  user: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
  problem: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    title?: string;
    /** Format: text */
    code?: string;
    /** Format: bigint */
    score?: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description answers */
  "body.answers": definitions["answers"];
  /** Format: bigint */
  "rowFilter.answers.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.answers.created_at": string;
  /** Format: text */
  "rowFilter.answers.text": string;
  /** Format: bigint */
  "rowFilter.answers.problem": string;
  /** Format: boolean */
  "rowFilter.answers.isCorrect": string;
  /** Format: text */
  "rowFilter.answers.desc": string;
  /** @description user */
  "body.user": definitions["user"];
  /** Format: bigint */
  "rowFilter.user.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.user.created_at": string;
  /** @description problem */
  "body.problem": definitions["problem"];
  /** Format: bigint */
  "rowFilter.problem.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.problem.created_at": string;
  /** Format: text */
  "rowFilter.problem.title": string;
  /** Format: text */
  "rowFilter.problem.code": string;
  /** Format: bigint */
  "rowFilter.problem.score": string;
}

export interface operations {}

export interface external {}
